const gen1Data = [
  {
    "Level": "1A",
    "Gen": "CYP2B6",
    "Fenotip": "Considerar dos gens CYP2B6 i CYP2C19 conjuntament",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "taula 2",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "Considerar dos gens CYP2B6 i CYP2C19 conjuntament",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "taula 2",
    "Font": "CPIC 2024",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "Considerar dos gens CYP2D6 i CYP2C19 conjunta",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Veure taula 2",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "Considerar dos gens CYP2D6 i CYP2C19 conjuntament",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Veure taula 2",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "Considerar dos gens CYP2D6 i CYP2C19 conjuntament",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Veure taula 2",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "Considerar dos gens CYP2D6 i CYP2C19 conjuntament",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Veure taula 2",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "Considerar dos gens CYP2D6 i CYP2C19 conjuntament",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Veure taula 2",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "CYP2C19  metabolitzador pobre ",
    "Família": "ISRS",
    "Fàrmac": "citalopram",
    "Recomanació": "Considerar alternativa que no es metabolitzi pel CYP2C19. Si s'utilitza, utilitzar dosi inicial més baixa, augment més progressiu i utilitzar el 50% de la dosi de manteniment dels metabolitzadors normals.",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "CYP2C19  metabolitzador pobre ",
    "Família": "ISRS",
    "Fàrmac": "escitalopram",
    "Recomanació": "Considerar alternativa que no es metabolitzi pel CYP2C19. Si s'utilitza, utilitzar dosi inicial més baixa, augment més progressiu i utilitzar el 50% de la dosi de manteniment dels metabolitzadors normals.",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "CYP2C19 metabolitzador intermedi",
    "Família": "ISRS",
    "Fàrmac": "citalopram",
    "Recomanació": "Dosi inicial recomanada. Considerar augment de dosi més gradual i dosis més baixes que metabolitzadors normals.",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "CYP2C19 metabolitzador intermedi",
    "Família": "ISRS",
    "Fàrmac": "escitalopram",
    "Recomanació": "Dosi inicial recomanada. Considerar augment de dosi més gradual i dosis més baixes que metabolitzadors normals.",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "CYP2C19 metabolitzador normal",
    "Família": "ISRS",
    "Fàrmac": "citalopram",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "CYP2C19 metabolitzador normal",
    "Família": "ISRS",
    "Fàrmac": "escitalopram",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "CYP2C19 metabolitzador ràpid ",
    "Família": "ISRS",
    "Fàrmac": "citalopram",
    "Recomanació": "Dosi inicial recomanada. Si no s'aconsegueix resposta amb dosi de manteniment, augmentar la dosi o canviar a un medicament que no es metabolitzi per CYP2C19",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "CYP2C19 metabolitzador ràpid ",
    "Família": "ISRS",
    "Fàrmac": "escitalopram",
    "Recomanació": "Dosi inicial recomanada. Si no s'aconsegueix resposta amb dosi de manteniment, augmentar la dosi o canviar a un medicament que no es metabolitzi per CYP2C19",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "CYP2C19 metabolitzador ultraràpid",
    "Família": "ISRS",
    "Fàrmac": "citalopram",
    "Recomanació": "Considerar alternativa que no es metabolitzi pel CYP2C19. Si s'utilitza, i no s'aconsegueix efecte desitjat amb dosis de manteniment habituals, considerar dosis més altes",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2C19",
    "Fenotip": "CYP2C19 metabolitzador ultraràpid",
    "Família": "ISRS",
    "Fàrmac": "escitalopram",
    "Recomanació": "Considerar alternativa que no es metabolitzi pel CYP2C19. Si s'utilitza, i no s'aconsegueix efecte desitjat amb dosis de manteniment habituals, considerar dosis més altes",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "Considerar dos gens CYP2D6 i CYP2C19 conjunta",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Veure taula 2",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "Considerar dos gens CYP2D6 i CYP2C19 conjuntament",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Veure taula 2",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "Considerar dos gens CYP2D6 i CYP2C19 conjuntament",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Veure taula 2",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "Considerar dos gens CYP2D6 i CYP2C19 conjuntament",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Veure taula 2",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "Considerar dos gens CYP2D6 i CYP2C19 conjuntament",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Veure taula 2",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 indeterminat",
    "Família": "Altres",
    "Fàrmac": "vortioxetina",
    "Recomanació": "No recomanació específica per aquest fenotip. Seguir pràctica clínica habitual.",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 indeterminat",
    "Família": "ISRN",
    "Fàrmac": "venlafaxina",
    "Recomanació": "No recomanació específica per aquest fenotip. Seguir pràctica clínica habitual.",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 indeterminat",
    "Família": "ISRS",
    "Fàrmac": "fluvoxamina",
    "Recomanació": "No recomanació específica per aquest fenotip. Seguir pràctica clínica habitual.",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 indeterminat",
    "Família": "ISRS",
    "Fàrmac": "paroxetina",
    "Recomanació": "No recomanació específica per aquest fenotip. Seguir pràctica clínica habitual.",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador intermedi (score 0,25-1)",
    "Família": "ADT",
    "Fàrmac": "nortriptilina",
    "Recomanació": "Reducció del 25% de la dosi inicial. Es recomana monitoratge farmacocinètic per ajustar la dosi.",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador intermedi (score 0,25-1)",
    "Família": "Altres",
    "Fàrmac": "vortioxetina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador intermedi (score 0,25-1)",
    "Família": "ISRN",
    "Fàrmac": "venlafaxina",
    "Recomanació": "No recomanació específica per aquest fenotip. Seguir pràctica clínica habitual.",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador intermedi (score 0,25-1)",
    "Família": "ISRS",
    "Fàrmac": "fluvoxamina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador intermedi (score 0,25-1)",
    "Família": "ISRS",
    "Fàrmac": "paroxetina",
    "Recomanació": "Considerar una dosi inicial menor i ajustar més lentament en comparació als metabolitzadors normals.",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador normal  (score 1,25,2,25)",
    "Família": "ADT",
    "Fàrmac": "nortriptilina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador normal (score 1,25,2,25)",
    "Família": "Altres",
    "Fàrmac": "vortioxetina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador normal (score 1,25,2,25)",
    "Família": "ISRN",
    "Fàrmac": "venlafaxina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador normal (score 1,25,2,25)",
    "Família": "ISRS",
    "Fàrmac": "fluvoxamina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador normal (score 1,25,2,25)",
    "Família": "ISRS",
    "Fàrmac": "paroxetina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador pobre",
    "Família": "ADT",
    "Fàrmac": "nortriptilina",
    "Recomanació": "Evitar ADT degut al potencial augment d'efectes adversos. Considerar utilitzar un fàrmac alternatiu no metabolitzat perl CYP2D6. Si s'ha d'utilitzar, iniciar amb una reducció del 50% en la dosi inicial i fer TDM per fer ajusts de dosi.",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador pobre (score 0)",
    "Família": "Altres",
    "Fàrmac": "vortioxetina",
    "Recomanació": "Reducció del 50% de la dosi inicial recomanada fins a una dosi màxima de 10 mg o bé considerar un antidepressiu alternatiu que no es metabolitzi principalment pel CYP2D6.",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador pobre (score 0)",
    "Família": "ISRN",
    "Fàrmac": "venlafaxina",
    "Recomanació": "Major risc d'efectes indesitjats. Si es possible, considerar un antidepressiu alternatiu que no es metabolitzi principalment pel CYP2D6.",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador pobre (score 0)",
    "Família": "ISRS",
    "Fàrmac": "fluvoxamina",
    "Recomanació": "Reducció del 25-50% de la dosi inicial i ajustar més lentament o bé considerar un antidepressiu alternatiu que no es metabolitzi principalment pel CYP2D6.",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador pobre (score 0)",
    "Família": "ISRS",
    "Fàrmac": "paroxetina",
    "Recomanació": "Reducció del 50% de la dosi inicial recomanada i titular més lentament. Dosi de manteniment un 50% menor en comparació als metabolitzadors normals.",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid",
    "Família": "ADT",
    "Fàrmac": "nortriptilina",
    "Recomanació": "Evitar ADT degut a falta d'eficàcia.Considerar utilitzar un fàrmac alternatiu no metabolitzat perl CYP2D6. Si no hi ha alternatives, es podria utilitzar una dosi de manteniment més alta de l'habitual si es disposa de monitoratge farmacocinètic",
    "Font": "CPIC 2016",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid (score >2,25)",
    "Família": "Altres",
    "Fàrmac": "vortioxetina",
    "Recomanació": "Considerar alternativa que no es metabolitzi pel CYP2D6. Si s'utilitza, iniciar amb la dosi inicial recomanada i titular la dosi de manteniment en base a l'efectivitat i els efectes adversos. Pot ser necessari augmentar la dosi de manteniment un 50% o més per assolir l'eficàcia.",
    "Font": "CPIC 2023",
    "comentari": "dosis diferents > 65 anys"
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid (score >2,25)",
    "Família": "ISRN",
    "Fàrmac": "venlafaxina",
    "Recomanació": "No recomanació específica per aquest fenotip. Seguir pràctica clínica habitual.",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid (score >2,25)",
    "Família": "ISRS",
    "Fàrmac": "fluvoxamina",
    "Recomanació": "No recomanació específica per aquest fenotip. Seguir pràctica clínica habitual.",
    "Font": "CPIC 2023",
    "comentari": NaN
  },
  {
    "Level": "1A",
    "Gen": "CYP2D6",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid (score >2,25)",
    "Família": "ISRS",
    "Fàrmac": "paroxetina",
    "Recomanació": "Considerar alternativa que no es metabolitzi principalment pel CYP2D6.",
    "Font": "CPIC 2023",
    "comentari": NaN
  }
];
const gen2Data = [
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si amitriptilina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si amitriptilina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús. Si amitriptilina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús. Si amitriptilina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": "Fitxa tècnica-CPIC-DPWG"
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús. Si es justifica un ADT, ajustar fins a una dosi objectiu més alta (en comparació amb els metabolitzadors normals). Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús. Si amitriptilina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar per possible resposta subòptima. Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si amitriptilina està justificada, disminuir un 50% la dosi inicial. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús. Si amitriptilina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús. Si amitriptilina està justificada, disminuir un 50% la dosi inicial. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si amitriptilina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús per possibles efectes adversos. Considerar un fàrmac alternatiu no metabolitzat pel CYP2D6. Si amitriptilina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús. Si amitriptilina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús. Si amitriptilina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar l'ús de tricíclics a causa de la possible manca d'eficàcia. Considerar un fàrmac alternatiu no metabolitzat pel CYP2D6. Si es justifica un ADT, ajustar fins a una dosi objectiu més alta (en comparació amb els metabolitzadors normals). Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús. Si amitriptilina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "amitriptilina",
    "Recomanació": "Evitar el seu ús. Si amitriptilina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si clomipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si clomipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús. Si clomipramina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús. Si clomipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús. Si es justifica un ADT, ajustar fins a una dosi objectiu més alta (en comparació amb els metabolitzadors normals). Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús. Si clomipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar per possible resposta subòptima. Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si clomipramina està justificada, disminuir un 50% la dosi inicial. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús. Si imipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús. Si clomipramina està justificada, disminuir un 50% la dosi inicial. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si clomipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús per possibles efectes adversos. Considerar un fàrmac alternatiu no metabolitzat pel CYP2D6. Si clomipramina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús. Si clomipramina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús. Si clomipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar l'ús de tricíclics a causa de la possible manca d'eficàcia. Considerar un fàrmac alternatiu no metabolitzat pel CYP2D6. Si es justifica un ADT, ajustar fins a una dosi objectiu més alta (en comparació amb els metabolitzadors normals). Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús. Si clomipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "clomipramina",
    "Recomanació": "Evitar el seu ús. Si clomipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si doxepina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si doxepina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús. Si doxepina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús. Si doxepina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús. Si es justifica un ADT, ajustar fins a una dosi objectiu més alta (en comparació amb els metabolitzadors normals). Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús. Si doxepina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar per possible resposta subòptima. Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si doxepina està justificada, disminuir un 50% la dosi inicial. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús. Si doxepina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús. Si doxepina està justificada, disminuir un 50% la dosi inicial. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si doxepina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús per possibles efectes adversos. Considerar un fàrmac alternatiu no metabolitzat pel CYP2D6. Si doxepina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús. Si doxepina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús. Si doxepina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar l'ús de tricíclics a causa de la possible manca d'eficàcia. Considerar un fàrmac alternatiu no metabolitzat pel CYP2D6. Si es justifica un ADT, ajustar fins a una dosi objectiu més alta (en comparació amb els metabolitzadors normals). Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús. Si doxepina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "doxepina",
    "Recomanació": "Evitar el seu ús. Si doxepina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si imipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si imipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús. Si imipramina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús. Si imipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús. Si es justifica un ADT, ajustar fins a una dosi objectiu més alta (en comparació amb els metabolitzadors normals). Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús. Si imipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar per possible resposta subòptima. Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si imipramina està justificada, disminuir un 50% la dosi inicial. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús. Si imipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús. Si imipramina està justificada, disminuir un 50% la dosi inicial. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si imipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús per possibles efectes adversos. Considerar un fàrmac alternatiu no metabolitzat pel CYP2D6. Si imipramina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús. Si imipramina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús. Si imipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar l'ús de tricíclics a causa de la possible manca d'eficàcia. Considerar un fàrmac alternatiu no metabolitzat pel CYP2D6. Si es justifica un ADT, ajustar fins a una dosi objectiu més alta (en comparació amb els metabolitzadors normals). Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús. Si imipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "imipramina",
    "Recomanació": "Evitar el seu ús. Si imipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2B6 metabolitzador indeterminat + CYP2C19 metabolitzador nornal",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2B6 metabolitzador indeterminat + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2B6 metabolitzador intermedi + CYP2C19 metabolitzador nornal",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals, augment més lent de la dosi de manteniment",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2B6 metabolitzador intermedi + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2B6 metabolitzador normal + CYP2C19 metabolitzador nornal",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2B6 metabolitzador nornal + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2B6 metabolitzador pobre + CYP2C19 metabolitzador nornal",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicial més baixa, disminuir el 25% la dosi de manteniment respecte metabolitzadors normals del CYP2B6, ajustant la dosi més lentament. Alternativa, canviar a antidepressiu que no es metabolitzi pel CYP2B6",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2B6 metabolitzador pobre + CYP2C19 metabolitzador ultràpid ràpid",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2B6 metabolitzador ultraràpid o ràpid + CYP2C19 metabolitzador normal",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2B6 metabolitzador ultraràpid o ràpid + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicial recomanada. Si no resposta,  utilitzar dosi de manteniment més alta o canviar antidepressiu  que no es metabolitzi pels CYP2C19 i CYP2B6",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador indeterminat + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador indeterminat + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals, augment més lent de la dosi de manteniment",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador indeterminat + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicial més baixa, disminuir el 50% la dosi de manteniment respecte metabolitzadors normals del CYP2C19, ajustant la dosi més lentament. Alternativa, canviar a antidepressiu que no es metabolitzi pel CYP2C19",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador intermedi + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals, augment més lent de la dosi de manteniment",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador intermedi + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals, augment més lent de la dosi de manteniment",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador intermedi + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicial més baixa, disminuir el 50% la dosi de manteniment respecte metabolitzadors normals del CYP2C19, ajustant la dosi més lentament. Alternativa, canviar a antidepressiu que no es metabolitzi pel CYP2C19",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador normal + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador normal + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals, augment més lent de la dosi de manteniment",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador normal + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicial més baixa, disminuir el 50% la dosi de manteniment respecte metabolitzadors normals del CYP2C19, ajustant la dosi més lentament. Alternativa, canviar a antidepressiu que no es metabolitzi pel CYP2C19",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador pobre + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicial més baixa, disminuir el 50% la dosi de manteniment respecte metabolitzadors normals del CYP2B6, ajustant la dosi més lentament. Alternativa, canviar a antidepressiu que no es metabolitzi pel CYP2B6",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador pobre + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Considerar alternativa que no es metabolitzi principalment pels CYP2C19 i CYP2B6",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador pobre+ CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicial més baixa, disminuir el 25% la dosi de manteniment respecte metabolitzadors normals del CYP2B6, ajustant la dosi més lentament. Alternativa, canviar a antidepressiu que no es metabolitzi pel CYP2B6",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador ultraràpid o ràpid + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador ultraràpid o ràpid + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador ultraràpid o ràpid + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicial més baixa, disminuir el 50% la dosi de manteniment respecte metabolitzadors normals del CYP2C19, ajustant la dosi més lentament. Alternativa, canviar a antidepressiu que no es metabolitzi pel CYP2C19",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si trimipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si trimipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús. Si trimipramina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús. Si trimipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús. Si es justifica un ADT, ajustar fins a una dosi objectiu més alta (en comparació amb els metabolitzadors normals). Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": " CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús. Si trimipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador indeterminat + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar per possible resposta subòptima. Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si trimipramina està justificada, disminuir un 50% la dosi inicial. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Disminuir un 25% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador intermedi + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús. Si trimipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "No hi ha recomanació",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador normal",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Iniciar amb la dosi inicial recomanada",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús. Si trimipramina està justificada, disminuir un 50% la dosi inicial. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador normal + CYP2C19 metabolitzador ultràpid o ràpid",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Considerar un fàrmac alternatiu no metabolitzat pel CYP2C19 (ex. nortriptilina). Si trimipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús per possibles efectes adversos. Considerar un fàrmac alternatiu no metabolitzat pel CYP2D6. Si trimipramina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús. Si trimipramina està justificada, disminuir un 50% la dosi inicial recomanada. Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador pobre + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús. Si trimipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador indeterminat",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar l'ús de tricíclics a causa de la possible manca d'eficàcia. Considerar un fàrmac alternatiu no metabolitzat pel CYP2D6. Si es justifica un ADT, ajustar fins a una dosi objectiu més alta (en comparació amb els metabolitzadors normals). Es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador intermedi",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús. Si trimipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2D6 metabolitzador ultraràpid + CYP2C19 metabolitzador pobre",
    "Gen": "CYP2D6 i CYP2C19",
    "Família": "ADT",
    "Fàrmac": "trimipramina",
    "Recomanació": "Evitar el seu ús. Si trimipramina està justificada, es recomana ajust de dosi segons monitoratge farmacocinètic.",
    "Font": "CPIC 2016",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  },
  {
    "Level": "1A",
    "Fenotip": "CYP2B6 metabolitzador normal + CYP2C19 metabolitzador ràpid o ultraràpid",
    "Gen": "CYP2B6 i CYP2C19",
    "Família": "ISRS",
    "Fàrmac": "sertralina",
    "Recomanació": "Dosis inicials habituals",
    "Font": "CPIC 2023",
    "Unnamed: 7": NaN,
    "Unnamed: 8": NaN,
    "Unnamed: 9": NaN,
    "Unnamed: 10": NaN,
    "Unnamed: 11": NaN,
    "Unnamed: 12": NaN
  }
];

document.addEventListener("DOMContentLoaded", () => {
  const genSelect = document.getElementById("gen-select");
  const farmSelect = document.getElementById("farmac-select");
  const resultContainer = document.getElementById("resultat");

  const uniqueGenes = [...new Set(gen1Data.map(row => row.Gen))].sort();
  uniqueGenes.forEach(gen => {
    const option = document.createElement("option");
    option.value = gen;
    option.textContent = gen;
    genSelect.appendChild(option);
  });

  genSelect.addEventListener("change", () => {
    farmSelect.innerHTML = '<option value="">-- Selecciona un fàrmac --</option>';
    const selectedGen = genSelect.value;
    const filtered = gen1Data.filter(row => row.Gen === selectedGen);
    const uniqueFarms = [...new Set(filtered.map(row => row["Fàrmac"]))].sort();
    uniqueFarms.forEach(farm => {
      const option = document.createElement("option");
      option.value = farm;
      option.textContent = farm;
      farmSelect.appendChild(option);
    });
    resultContainer.innerHTML = "";
  });

  farmSelect.addEventListener("change", () => {
    const selectedGen = genSelect.value;
    const selectedFarm = farmSelect.value;
    const filtered = gen1Data.filter(row => row.Gen === selectedGen && row["Fàrmac"] === selectedFarm);

    if (filtered.length > 0) {
      resultContainer.innerHTML = "";
      filtered.forEach(row => {
        const card = document.createElement("div");
        card.className = "bg-blue-50 rounded-xl shadow p-4 my-4 border border-blue-200";
        card.innerHTML = `
          <h3 class="text-lg font-semibold text-blue-900">${row["Gen"]} - ${row["Fàrmac"]}</h3>
          <p><strong>Fenotip:</strong> ${row["Fenotip"]}</p>
          <p><strong>Família:</strong> ${row["Família"]}</p>
          <p><strong>Recomanació:</strong> ${row["Recomanació"]}</p>
          <p><strong>Font:</strong> ${row["Font"]}</p>
        `;
        resultContainer.appendChild(card);
      });
    } else {
      resultContainer.innerHTML = "<p class='text-red-600'>No s'ha trobat cap recomanació.</p>";
    }
  });
});
